log:
  console:
    level: info
    isJson: true
    color: false
  file:
    enable: false
    name: ./console_log.log
    level: info
    isJson: true

database:
  dbName: test_local
  protocol: tcp
  maxOpenConns: 20
  maxIdleConns: 10
  connMaxLifeTimeSec: 3600
  connMaxIdleTimeSec: 1200
  retryTimeInSec: 30
  countRetry: 5

server:
  port: 8080
  contextPath: /mock_server_loacal
  name: mock_server_loacal
  version: v0.1.0
  bodyLimit: -1
  readTimeoutSec: 60
  wrtieTimeoutSec: 60
